2 task
js-tasks-ru/js-20210806_olga-nikolaevna2005 pull request #2
Opened 2021-08-15 15:11 UTC by olga-nikolaevna

2021-08-15 15:12 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-08-15 20:21 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let result = arr.slice().sort((a, b) => a.localeCompare(b, ['ru-u-kf-upper','en-u-kf-upper']));
проверьте, а точно ли тут `let`?

2021-08-15 20:21 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +       return result.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-08-15 20:23 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +   else 	return result;
когда в блоке `if` есть `return` то блок `else` можно убрать вот таким образом:
```
if (param === 'desc') {
  return ...
}

return result;
```

2021-08-15 20:24 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let new_fruits = new Object();
пожалуйста для объявления переменных используйте `camelCase` нотацию.
Объект следует объявлять через литера, вот так: `const obj = {}`
проверьте, а точно ли здесь нужно использовать `let`? мы ведь не присваиваем переменно другое значение, а только меняем значения внутри объекта

2021-08-15 20:25 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +        if (obj.hasOwnProperty(elem)) {delete obj[elem];}
на занятии мы разбирали что `delete` не следует использовать на объектах?
помните почему?

2021-08-15 20:26 UTC, dosandk requested changes
необходимо внести правки согласно комментариев, дать ответ на вопрос

2021-08-24 13:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-24 13:30 UTC, olga-nikolaevna commented on 02-javascript-data-types/3-omit/index.js
> +        if (obj.hasOwnProperty(elem)) {delete obj[elem];}
Delete удаляет элемент в объекте, на который могут ссылаться другие переменные, поэтому его не рекомендуется использовать :)

2021-08-24 14:09 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-08-24 16:00 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +	return arr.slice().sort((a, b) => a.localeCompare(b, ['ru-u-kf-upper','en-u-kf-upper']));
9 и 10 строки дублируют друг друга. Решение, вынести логику сортировки в отдельную функцию

2021-08-24 16:00 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +        if (obj.hasOwnProperty(elem)) {delete obj[elem];}
👍

2021-08-24 16:00 UTC, dosandk approved these changes
good 👍

2021-08-24 16:01 UTC, merged